const ytTutorialUrl = "https://www.youtube.com/watch?v=0uL0ig1F05k&ab_channel=Shoper";
export const MESSAGES = {
  pl: {
    required: "To pole jest wymagane",
    required_checkbox: "To pole musi zostać zaznaczone",
    email: "Wprowadź adres w formacie: nazwa@domena.pl",
    phone: "Wprowadź numer składający się z 9 cyfr w formacie: 123456789",
    text: "Wprowadź minimum 2 znaki",
    postcode: 'Wprowadź poprawny kod pocztowy w formacie: XX-XXX lub XXXXX',
    nip: "Wprowadź poprawny numer NIP w formacie: 1234567890 lub XX1234567890",
    0: `Podczas uruchamiania wersji testowej sklepu wystąpił problem techniczny. Spróbuj ponownie później.`,
    1: `Podczas uruchamiania wersji testowej sklepu wystąpił problem techniczny. Spróbuj ponownie później. O tym, jak założyć sklep i poprawnie się zalogować, dowiesz się z naszego <a class="link" href="${ytTutorialUrl}">wideoporadnika.</a>`,
    2: `Uruchomiłeś co najmniej cztery wersje testowe sklepu w zbyt krótkim czasie. Odczekaj 24h od ostatniej udanej próby, zanim zrobisz to ponownie. O tym, jak założyć sklep i poprawnie się zalogować, dowiesz się z naszego <a href="${ytTutorialUrl}">wideoporadniku.</a>`,
    3: `Próbujesz uruchomić więcej niż jedną wersję testową sklepu w zbyt krótkim czasie. Odczekaj co najmniej godzinę, zanim zrobisz to ponownie. O tym, jak założyć sklep i poprawnie się zalogować, dowiesz się z naszego <a href="${ytTutorialUrl}">wideoporadniku.</a>`,
    4: `Próbujesz uruchomić więcej niż jedną wersję testową sklepu w zbyt krótkim czasie. Odczekaj kilka minut, zanim zrobisz to ponownie. O tym, jak założyć sklep i poprawnie się zalogować, dowiesz się z naszego <a href="${ytTutorialUrl}">wideoporadniku.</a>`,
  },
  en: {
    required: "This field is required",
    required_checkbox: "This box must be checked",
    email: "Please enter a valid email address",
    phone: "Minimum 9 digits",
    text: "Minimum 3 characters",
    postcode: 'Wprowadź poprawny kod pocztowy w formacie: XX-XXX lub XXXXX',
    nip: "Wprowadź poprawny numer NIP w formacie: 1234567890 lub XX1234567890",
    0: `Podczas uruchamiania wersji testowej sklepu wystąpił problem techniczny. Spróbuj ponownie później.`,
    1: `Podczas uruchamiania wersji testowej sklepu wystąpił problem techniczny. Spróbuj ponownie później. O tym, jak założyć sklep i poprawnie się zalogować, dowiesz się z naszego <a class="link" href="${ytTutorialUrl}">wideoporadnika.</a>`,
    2: `Uruchomiłeś co najmniej cztery wersje testowe sklepu w zbyt krótkim czasie. Odczekaj 24h od ostatniej udanej próby, zanim zrobisz to ponownie. O tym, jak założyć sklep i poprawnie się zalogować, dowiesz się z naszego <a href="${ytTutorialUrl}">wideoporadniku.</a>`,
    3: `Próbujesz uruchomić więcej niż jedną wersję testową sklepu w zbyt krótkim czasie. Odczekaj co najmniej godzinę, zanim zrobisz to ponownie. O tym, jak założyć sklep i poprawnie się zalogować, dowiesz się z naszego <a href="${ytTutorialUrl}">wideoporadniku.</a>`,
    4: `Próbujesz uruchomić więcej niż jedną wersję testową sklepu w zbyt krótkim czasie. Odczekaj kilka minut, zanim zrobisz to ponownie. O tym, jak założyć sklep i poprawnie się zalogować, dowiesz się z naszego <a href="${ytTutorialUrl}">wideoporadniku.</a>`,
  },
};
